WindRiver-OpenSourceLabs/wrlabs-integration

- recipes-core/glib-2.0/glib-2.0_2.44.1.bbappend
- recipes-devtools/elfutils/elfutils/0001-Remove-redundant-NULL-tests.patch
- recipes-devtools/elfutils/elfutils/0001-libebl-Fix-missing-brackets-around-if-statement-body.patch
- recipes-devtools/elfutils/elfutils_0.163.bbappend
- recipes-devtools/pkgconfig/pkgconfig_git.bbappend
The following commits resolve the host build failure on Fedora 24 with GCC6.
> pkgconfig-native: work around the build failure with gcc >=6.0

- recipes-devtools/openjade/openjade-native_1.3.2.bbappend
- openjade-native: backported from oe-core
> Bug fixes for supporting GCC 6

- templates/default/template.conf
All essential-only package groups will be conditionally installed if the
corresponding DISTRO_FEATURES/MACHINE_FEATURES is defined.
> Clean up essential-only package groups

- templates/default/template.conf
> cube-builder-initramfs: use CUBE_BUILDER_INITRAMFS_EXTRA_INSTALL to add extra packages

- templates/default/template.conf
initramfs needs to be defined globally to allow to do_bundle_initramfs()
during the kernel build.
> Define the initramfs globally for x86 machines

- templates/default/template.conf
Note only initramfs image is not included.
> wrlabs: define CUBE_COMMON_INSTALL for the installation on all cubes

- templates/default/template.conf
kernel-initramfs-image provides the initramfs image and it should be
installed as long as initramfs is defined for a real rootfs image.
> wrlab: install kernel-initramfs-image as long as initramfs used

- recipes-bsp/grub/grub-efi/grub-runtime.cfg
- recipes-bsp/grub/grub-efi_2.00.bbappend
The Pulsar Linux always provides a default grub config file for the installer
and the build system can sign it during the build progress.
> grub-efi: install the grub-installer.cfg for Pulsar Linux

- recipes-bsp/grub/grub-efi/grub-runtime.cfg
Current grub doesn't support to set the fallback to title.
> grub-efi: set the fallback to entry number

- templates/default/template.conf
rpm-signing feature is not enabled by default with meta-secure-env.
> wrlab: don't always install key-store-rpm-pubkey

- recipes-bsp/grub/grub-efi_2.00.bbappend
grub.cfg.p7b may not exist if uefi-secure-boot is not configured.
In this case, do_deploy() fails checking the return value set by
the condition statement. To fix this issue, just adjust the position
of the condition statement.
> grub-efi: fix do_deploy() failure if uefi-secure-boot is not configured

- templates/default/template.conf
- templates/feature/efi-secure-boot/README
- templates/feature/efi-secure-boot/image.inc
- templates/feature/efi-secure-boot/template.conf
- templates/feature/encrypted-storage/README
- templates/feature/encrypted-storage/image.inc
- templates/feature/encrypted-storage/require
- templates/feature/encrypted-storage/template.conf
- templates/feature/ima/README
- templates/feature/ima/image.inc
- templates/feature/ima/require
- templates/feature/ima/template.conf
- templates/feature/tpm/image.inc
- templates/feature/tpm/template.conf
- templates/feature/tpm2/README
- templates/feature/tpm2/image.inc
- templates/feature/tpm2/template.conf
All templates for security features are not maintained in the dedicated
security layer.
> wrlabs-integration: integrate the templates for security features

- conf/layer.conf
wrlab-integration is designed to overwrite some settings in higher prority
so set the priority to 20 over all other layers.
> wrlab-integration: increase the layer priority

- templates/feature/ima/template.conf
The same logic was removed in layer.conf from meta-integrity.
Signed-off-by: Jia Zhang <lans.zhang2008@gmail.com>
> feature/ima: inherit sign_rpm_ext

- recipes-bsp/grub/grub-efi_2.02.bbappend
Otherwise signed grub image in ${D} is replaced by unsigned one, hence the
unsigned one is packaged into RPM.
That is not a right behavior.
Signed-off-by: Yunguo Wei <yunguo.wei@windriver.com>
> grub-efi: Do not overwrite signed grub efi bianry when secure boot is enabled

- recipes-extended/packagegroups/packagegroup-samples.bb
- recipes-extended/packagegroups/packagegroup-webserver.bb
- recipes-samples/gcc-example/gcc-example_1.0.bb
- recipes-support/rpm-tool/nativesdk-rpm-tool_1.0.bb
The top level LICENSE file is not actually a license, it refers
other licenses that are used by Bitbake and Meta-data. Relying
on this file could cause problems for recipes when this file
changes, which it is about to.
Signed-off-by: Ming Liu <ming.liu@windriver.com>
> meta: drop ${COREBASE}/LICENSE references

- recipes-extended/libsolv/files/0001-repo_rpmdb.c-increase-MAX_HDR_CNT-and-MAX_HDR_DSIZE.patch
- recipes-extended/libsolv/libsolv_0.6.28.bbappend
We encountered a problem when installing kernel-devsrc package on a
intel-x86 target, as follows:
$ dnf install kernel-devsrc
...
Installing : kernel-devsrc-1.0-r0.0.intel_corei7_64 1/1
failed loading RPMDB
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
...
It can be fixed by increasing MAX_HDR_CNT and MAX_HDR_DSIZE in libsolv
per test.
Signed-off-by: Ming Liu <ming.liu@windriver.com>
> libsolv: fix a kernel-devsrc installation issue

- recipes-bsp/shim/shim_git.bbappend
fallback has some problem with MOK verify protocol, so taking it out.
This is a temp patch, will be removed when upstream integrates this
change.
The following warning will be shown, but ignore them for now:
WARNING: shim-12+gitAUTOINC+5202f80c32-r0 do_package: QA Issue: shim:
Files/directories were installed but not shipped in any package:
/boot/efi/EFI/BOOT/bootx64.csv
/boot/efi/EFI/BOOT/fbx64.efi
Signed-off-by: Yunguo Wei <yunguo.wei@windriver.com>
> shim: taking fallback out from secure boot

- recipes-support/rpm-tool/nativesdk-rpm-tool_1.0.bb
We don't needd ima-tool anymore, as IMA signing is done via 'rpmsign'.
repo-tool is integrated into rpm-tool.
Signed-off-by: Yunguo Wei <yunguo.wei@windriver.com>
> Remove ima-tool and repo-tool

- recipes-support/rpm-tool/rpm-tool/rpm-tool
1. Add --pkg-arch option to specify a package's architecture
2. Minor fix for help info.
> Fixes for rpm-tool

- recipes-core/dbus/dbus_1.8.20.bbappend
- recipes-core/dbus/files/0001-generate-machine-id-in-dbus-service.patch
Issue: LINPUL8-764
Add command 'dbus-uuidgen --ensure' in dbus service and rpm
postinstall script to generate /var/lib/dbus/machine-id which is
used to backup the machine-id for systemd.
Signed-off-by: De Huo <De.Huo@windriver.com>
> dbus: fix defect about machine id change after system upgrade

- scripts/lib/wic/canned-wks/cube-gw-ostree-runtime-nxp-imx6.wks
- scripts/lib/wic/canned-wks/seco-image-minimal-ostree-runtime-nxp-imx6.wks
Reserve 1M space for bootloader in wks for nxp-imx6 bsp.
Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
> nxp-imx:reserve 1M space for bootloader in wks
